name = "playhtml5-games"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "npm run build"

[env.production]
name = "playhtml5-games-prod"

[env.staging]
name = "playhtml5-games-staging" 